# Generated by Django 3.2.5 on 2021-12-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_payment_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.userproduct'),
        ),
    ]
