# Generated by Django 3.2.5 on 2021-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_Mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
