# Generated by Django 3.2.5 on 2021-12-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_Mode',
        ),
    ]
