# Generated by Django 3.2.5 on 2021-12-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
